# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'

development:
  adapter: postgresql
  encoding: utf8
  database: liwi-dev
  pool: 10
  timeout: 4
  username: postgres
  password: root
#  url: postgres://rsatqeudafkjyx:e49c00cceb37a34b2c72541db5f82df7bdebc94ab838862c63d2424b94637c20@ec2-46-137-124-19.eu-west-1.compute.amazonaws.com:5432/dbjkihe8tjm9ut
#  url: postgres://postgres:7b50cecaf8ef415df0c5fb968e37608c@liwi-test.wavelab.top:1872/liwi_test # allow to test with ctlq database
#  url: postgres://postgres:e6ad100af582bb53b3e23ea0c98b056a@medalc.unisante.ch:32462/medalc # allow to test with prod database

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test:
  adapter: postgresql
  encoding: utf8
  database: liwi-test
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['PROD_DB_NAME'] %>
  pool: 5
  username: <%= ENV['PROD_DB_USERNAME'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
